version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "Saraphite"
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      production-dependencies:
        patterns:
          - "Microsoft.*"
          - "System.*"
      development-dependencies:
        patterns:
          - "*.Test.*"
          - "xunit*"
          - "coverlet*"
        
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "Saraphite"
    commit-message:
      prefix: "ci"
      include: "scope"
