name: Release

on:
  push:
    tags: [ 'v*' ]

env:
  DOTNET_VERSION: '8.0.x'
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v1.1.1
      with:
        versionSpec: '5.x'
    
    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v1.1.1
      id: gitversion
      with:
        useConfigFile: true
    
    - name: Display Version
      run: |
        echo "NuGet Version: ${{ steps.gitversion.outputs.nuGetVersionV2 }}"
        echo "Assembly Version: ${{ steps.gitversion.outputs.assemblySemVer }}"
        echo "Tag Name: ${{ github.ref_name }}"
    
    - name: Restore dependencies
      run: dotnet restore CloakId.sln
    
    - name: Build solution
      run: dotnet build CloakId.sln --no-restore --configuration Release
      env:
        VersionPrefix: ${{ steps.gitversion.outputs.majorMinorPatch }}
        VersionSuffix: ${{ steps.gitversion.outputs.preReleaseTag }}
        Version: ${{ steps.gitversion.outputs.nuGetVersionV2 }}
    
    - name: Run tests
      run: dotnet test CloakId.sln --no-build --configuration Release --verbosity normal
    
    - name: Pack NuGet packages
      run: |
        dotnet pack src/CloakId/CloakId.csproj --no-build --configuration Release --output ./packages
        dotnet pack src/CloakId.AspNetCore/CloakId.AspNetCore.csproj --no-build --configuration Release --output ./packages
        dotnet pack src/CloakId.Sqids/CloakId.Sqids.csproj --no-build --configuration Release --output ./packages
      env:
        VersionPrefix: ${{ steps.gitversion.outputs.majorMinorPatch }}
        VersionSuffix: ${{ steps.gitversion.outputs.preReleaseTag }}
        Version: ${{ steps.gitversion.outputs.nuGetVersionV2 }}
    
    - name: Generate release notes
      id: release_notes
      run: |
        # Get commits since last tag
        PREVIOUS_TAG=$(git describe --tags --abbrev=0 HEAD~1 2>/dev/null || echo "")
        if [ -z "$PREVIOUS_TAG" ]; then
          COMMITS=$(git log --pretty=format:"- %s (%h)" --reverse)
        else
          COMMITS=$(git log ${PREVIOUS_TAG}..HEAD --pretty=format:"- %s (%h)" --reverse)
        fi
        
        # Create release notes
        echo "## What's Changed" > release_notes.md
        echo "" >> release_notes.md
        echo "$COMMITS" >> release_notes.md
        echo "" >> release_notes.md
        echo "**Full Changelog**: https://github.com/${{ github.repository }}/compare/${PREVIOUS_TAG}...${{ github.ref_name }}" >> release_notes.md
        
        cat release_notes.md
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body_path: release_notes.md
        files: ./packages/*.nupkg
        draft: false
        prerelease: ${{ steps.gitversion.outputs.preReleaseTag != '' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Publish to NuGet
      run: |
        dotnet nuget push ./packages/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
    
    - name: Publish to GitHub Packages
      run: |
        dotnet nuget push ./packages/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/Saraphite/index.json --skip-duplicate
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
